"""
cv_splits.py -- CV Split Builder (v3 Final)

Phase 1: Writes a stratified PLACEHOLDER split (NOT scanner-aware).
         EDA/notebook convenience only.
          DO NOT USE FOR MODEL TRAINING 

Phase 3: StratifiedGroupKFold on pre-scanned DICOM scanner fingerprints.
         - Groups by scanner fingerprint (eliminates +0.053 AUC leakage)
         - Stratifies on is_gold indicator (prevents rare label clustering in folds)
         - Fingerprint tags read from config, never hardcoded
         - Requires dicom_fingerprints.csv from scan_dicom_fingerprints.py
         - Requires sklearn >= 1.6

Note: train_series.csv does NOT contain scanner metadata -- it only has
      StudyInstanceUID, SeriesInstanceUID, Fluid_Sensitive, Fat_Suppression,
      Anatomical_Plane. Do not attempt to read Manufacturer/ModelName from it.
"""

from __future__ import annotations

import warnings
from pathlib import Path
from typing import Optional

import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold, StratifiedKFold


# =============================================================================
# PHASE 1 -- PLACEHOLDER SPLIT (EDA use only)
# =============================================================================

def build_placeholder_split(
    train_df: pd.DataFrame,
    n_folds: int,
    output_path: str,
    label_cols: list[str],
    seed: int = 42,
) -> pd.DataFrame:
    """Build a stratified placeholder CV split for Phase 1 EDA purposes only.

     WARNING: This split is NOT scanner-aware and MUST NOT be used for
    model training. Random stratified splits cause +0.053 AUC leakage from
    scanner/site fingerprint memorization.
    See: docs/discussions/03_dicom_metadata_shortcut_analysis.md

    Args:
        train_df: DataFrame from train.csv (4,407 rows)
        n_folds: Number of CV folds (5)
        output_path: Path to write the placeholder CSV
        label_cols: List of 12 label column names (from config.yaml)
        seed: Random seed for reproducibility

    Returns:
        DataFrame with StudyInstanceUID, fold_id, is_gold, split_type columns.
    """
    is_gold = train_df["ACL"].notna().astype(int)

    skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=seed)
    fold_ids = pd.Series(-1, index=train_df.index)

    for fold_idx, (_, val_idx) in enumerate(skf.split(train_df.index, is_gold)):
        fold_ids.iloc[val_idx] = fold_idx

    assert (fold_ids == -1).sum() == 0, "Bug: some rows were not assigned a fold!"

    out_df = pd.DataFrame({
        "StudyInstanceUID": train_df["StudyInstanceUID"].values,
        "fold_id": fold_ids.values,
        "is_gold": is_gold.values,
        "split_type": "PLACEHOLDER_STRATIFIED_NOT_FOR_TRAINING",
    })

    gold_per_fold = out_df[out_df["is_gold"] == 1]["fold_id"].value_counts()
    folds_without_gold = [
        f for f in range(n_folds) if f not in gold_per_fold.index
    ]
    if folds_without_gold:
        warnings.warn(
            f"Placeholder split has fold(s) with ZERO gold studies: "
            f"{folds_without_gold}. "
            f"Gold distribution: {gold_per_fold.sort_index().to_dict()}. "
            f"This is not authoritative, but investigate before EDA use.",
            UserWarning,
            stacklevel=2,
        )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(output_path, index=False)

    print("WARNING: PLACEHOLDER SPLIT WRITTEN (NOT for model training):")
    print("   Path:          " + str(output_path))
    print("   Fold sizes:    " + str(out_df["fold_id"].value_counts().sort_index().to_dict()))
    print("   Gold per fold: " + str(gold_per_fold.sort_index().to_dict()))
    print("   Real scanner-aware split will be built in Phase 3 on Kaggle.")

    return out_df


# =============================================================================
# PHASE 3 -- StratifiedGroupKFold with DICOM-scanned fingerprints
# =============================================================================

def build_scanner_fingerprint_split(
    train_df: pd.DataFrame,
    fingerprints_csv: str,
    n_folds: int,
    output_path: str,
    fingerprint_tags: list[str],
    seed: int = 42,
    patient_id_col: Optional[str] = "PatientID",
) -> pd.DataFrame:
    """Build scanner-aware StratifiedGroupKFold CV split (Phase 3, Kaggle only).

    Requires dicom_fingerprints.csv pre-generated by scan_dicom_fingerprints.py.
    This replaces the v1 stub that raised NotImplementedError.

    Key design choices vs plain GroupKFold:
        - StratifiedGroupKFold: simultaneously groups on scanner fingerprint
          AND stratifies on is_gold, preventing rare gold labels (MCL=9,
          Baker's=12) from clustering in a single fold.
        - Fingerprint tags read from config.yaml (not hardcoded).
        - Always prints fold sizes + gold per fold -- do not assume balance.

    Args:
        train_df: DataFrame from train.csv (4,407 rows).
        fingerprints_csv: Path to dicom_fingerprints.csv (from scan step).
        n_folds: Number of CV folds (5).
        output_path: Path to write cv_folds_5fold.csv.
        fingerprint_tags: DICOM tag names from config.yaml cv.fingerprint_tags.
        seed: StratifiedGroupKFold random state (requires sklearn >= 1.6).
        patient_id_col: Optional column for patient-level group dedup.

    Returns:
        DataFrame with StudyInstanceUID, fold_id, scanner_fingerprint, is_gold.

    Raises:
        FileNotFoundError: If dicom_fingerprints.csv doesn't exist.
        RuntimeError: If sklearn < 1.6.
        ValueError: If no fingerprint tags found in the scanned CSV.
    """
    import sklearn
    from packaging import version as pkg_version

    if pkg_version.parse(sklearn.__version__) < pkg_version.parse("1.6"):
        raise RuntimeError(
            f"scikit-learn >= 1.6 required for StratifiedGroupKFold(shuffle=True). "
            f"Found: {sklearn.__version__}."
        )

    if not Path(fingerprints_csv).exists():
        raise FileNotFoundError(
            f"dicom_fingerprints.csv not found: {fingerprints_csv}\n"
            "Run `python scripts/scan_dicom_fingerprints.py` first on Kaggle.\n"
            "Note: train_series.csv does NOT contain scanner metadata."
        )

    fp_df = pd.read_csv(fingerprints_csv)

    # Tags read from config -- verify they exist in the scanned CSV
    available_tags = [t for t in fingerprint_tags if t in fp_df.columns]
    missing_tags   = [t for t in fingerprint_tags if t not in fp_df.columns]
    if missing_tags:
        warnings.warn(
            f"Fingerprint tags missing from CSV (will be skipped): {missing_tags}. "
            f"Re-run scan_dicom_fingerprints.py with updated config.",
            UserWarning, stacklevel=2,
        )
    if not available_tags:
        raise ValueError(
            f"No fingerprint tags found in {fingerprints_csv}. "
            f"Requested: {fingerprint_tags}. Available: {fp_df.columns.tolist()}"
        )

    if "scanner_fingerprint" not in fp_df.columns:
        fp_df["scanner_fingerprint"] = (
            fp_df[available_tags].fillna("UNKNOWN").astype(str)
            .apply(lambda row: "|".join(row), axis=1)
        )

    train_df = train_df.merge(
        fp_df[["StudyInstanceUID", "scanner_fingerprint"]],
        on="StudyInstanceUID", how="left",
    )
    n_missing = train_df["scanner_fingerprint"].isna().sum()
    if n_missing > 0:
        warnings.warn(
            f"{n_missing} studies have no fingerprint match -- assigning 'UNKNOWN'.",
            UserWarning, stacklevel=2,
        )
        train_df["scanner_fingerprint"] = train_df["scanner_fingerprint"].fillna("UNKNOWN")

    # Build group key: optionally dedup at patient level
    if patient_id_col and patient_id_col in train_df.columns:
        train_df["_group_key"] = (
            train_df[patient_id_col].astype(str) + "_"
            + train_df["scanner_fingerprint"].astype(str)
        )
        print("Group key: PatientID + scanner_fingerprint")
    else:
        train_df["_group_key"] = train_df["scanner_fingerprint"]
        print("Group key: scanner_fingerprint only")

    group_codes = pd.Categorical(train_df["_group_key"]).codes
    n_groups = len(set(group_codes))
    print("Unique groups:", n_groups, "| Fingerprints:", train_df["scanner_fingerprint"].nunique())

    # StratifiedGroupKFold: group=scanner, stratify=is_gold
    is_gold = train_df["ACL"].notna().astype(int)

    fold_ids = pd.Series(-1, index=train_df.index)

    if n_groups >= n_folds:
        # Normal path: enough distinct scanner groups for GroupKFold
        sgkf = StratifiedGroupKFold(n_splits=n_folds, shuffle=True, random_state=seed)
        for fold_idx, (_, val_idx) in enumerate(
            sgkf.split(train_df.index, y=is_gold, groups=group_codes)
        ):
            fold_ids.iloc[val_idx] = fold_idx
        split_type = "SCANNER_FINGERPRINT_STRATIFIEDGROUPKFOLD"
    else:
        # Fallback: DICOM scan returned mostly UNKNOWN (e.g. DICOM path inaccessible).
        # Use plain StratifiedKFold on individual studies.
        # WARNING: this fallback does NOT control scanner-fingerprint leakage.
        warnings.warn(
            f"Only {n_groups} unique scanner group(s) found (expected >= {n_folds}). "
            "DICOM fingerprint scan likely failed -- all studies tagged UNKNOWN. "
            "Falling back to plain StratifiedKFold. "
            "Scanner-fingerprint leakage is NOT controlled in this split.",
            UserWarning, stacklevel=2,
        )
        skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=seed)
        for fold_idx, (_, val_idx) in enumerate(skf.split(train_df.index, y=is_gold)):
            fold_ids.iloc[val_idx] = fold_idx
        split_type = "FALLBACK_STRATIFIEDKFOLD_NO_SCANNER_GROUPING"

    assert (fold_ids == -1).sum() == 0, "Bug: some rows unassigned!"

    out_df = pd.DataFrame({
        "StudyInstanceUID": train_df["StudyInstanceUID"].values,
        "fold_id": fold_ids.values,
        "scanner_fingerprint": train_df["scanner_fingerprint"].values,
        "is_gold": is_gold.values,
        "split_type": split_type,
    })

    # Validation checks
    gold_per_fold = out_df[out_df["is_gold"] == 1]["fold_id"].value_counts()
    folds_without_gold = [f for f in range(n_folds) if f not in gold_per_fold.index]
    if folds_without_gold:
        warnings.warn(
            f"Folds with no gold studies: {folds_without_gold}. "
            f"Distribution: {gold_per_fold.sort_index().to_dict()}.",
            UserWarning, stacklevel=2,
        )

    fold_sizes = out_df["fold_id"].value_counts().sort_index()
    max_imbalance = fold_sizes.max() / fold_sizes.min()
    if max_imbalance > 1.5:
        warnings.warn(
            f"Fold size imbalance {max_imbalance:.2f}x -- {fold_sizes.to_dict()}",
            UserWarning, stacklevel=2,
        )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(output_path, index=False)

    print("Split written:", output_path)
    print("Split type:", split_type)
    print("Fold sizes:", fold_sizes.to_dict())
    print("Gold per fold:", gold_per_fold.sort_index().to_dict())
    return out_df
